
export const getDefs = [
    {"Targets": [
        {
            "Dec": 41.26875,
            "DecOffset": -1.9,
            "PA": 32,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 10.684708333333331,
            "RAOffset": 12.1,
            "acquisition": "guider: offset",
            "comment": "Galaxies are boring",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9232414932803,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 8.7,
                "V": 2.3
            },
            "name": "M31",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "north",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": 31.31,
            "DecOffset": null,
            "PA": 22.5,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 52.297,
            "RAOffset": null,
            "acquisition": "blind",
            "comment": "Low mass star formation is the coolest",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9232414936914,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "NGC1333",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": null,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.16560286,
            "DecOffset": null,
            "PA": 0,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 349.99333127,
            "RAOffset": null,
            "acquisition": "guider: bright",
            "comment": "I guess we need a standard",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.923241493945,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "Feige110",
            "objecttype": "flux standard",
            "obstime": null,
            "rotmode": "vertical",
            "wrap": null,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.123176313398065,
            "DecOffset": -4.5,
            "PA": 90,
            "PMDec": -10,
            "PMRA": 10,
            "RA": 82.62368200885628,
            "RAOffset": 8.4,
            "acquisition": "guider: offset",
            "comment": "Star formation is cool",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9724429395196,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 6.7,
                "V": 4.3
            },
            "name": "M42",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "shortest",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": 41.26875,
            "DecOffset": -1.9,
            "PA": 32,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 10.684708333333331,
            "RAOffset": 12.1,
            "acquisition": "guider: offset",
            "comment": "Galaxies are boring",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9724429398525,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 8.7,
                "V": 2.3
            },
            "name": "M31",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "north",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": 31.31,
            "DecOffset": null,
            "PA": 22.5,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 52.297,
            "RAOffset": null,
            "acquisition": "blind",
            "comment": "Low mass star formation is the coolest",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9724429399932,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "NGC1333",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": null,
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.16560286,
            "DecOffset": null,
            "PA": null,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 349.99333127,
            "RAOffset": null,
            "acquisition": "guider: bright",
            "comment": "I guess we need a standard",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.972442940135,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "Feige110",
            "objecttype": "flux standard",
            "obstime": null,
            "rotmode": "vertical",
            "wrap": null,
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.123176322743254,
            "DecOffset": -4.5,
            "PA": 90,
            "PMDec": -10,
            "PMRA": 10,
            "RA": 82.62368201824252,
            "RAOffset": 8.4,
            "acquisition": "guider: offset",
            "comment": "Star formation is cool",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.972446390957,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 6.7,
                "V": 4.3
            },
            "name": "M42",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "shortest",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": 41.26875,
            "DecOffset": -1.9,
            "PA": 32,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 10.684708333333331,
            "RAOffset": 12.1,
            "acquisition": "guider: offset",
            "comment": "Galaxies are boring",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9724463914727,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 8.7,
                "V": 2.3
            },
            "name": "M31",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "north",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": 31.31,
            "DecOffset": null,
            "PA": 22.5,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 52.297,
            "RAOffset": null,
            "acquisition": "blind",
            "comment": "Low mass star formation is the coolest",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.972446391626,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "NGC1333",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": null,
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.16560286,
            "DecOffset": null,
            "PA": null,
            "PMDec": 0,
            "PMRA": 0,
            "RA": 349.99333127,
            "RAOffset": null,
            "acquisition": "guider: bright",
            "comment": "I guess we need a standard",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9724463917742,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {},
            "name": "Feige110",
            "objecttype": "flux standard",
            "obstime": null,
            "rotmode": "vertical",
            "wrap": null,
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "Dec": -5.123043094390277,
            "DecOffset": -4.5,
            "PA": 90,
            "PMDec": -10,
            "PMRA": 10,
            "RA": 82.62354820459252,
            "RAOffset": 8.4,
            "acquisition": "guider: offset",
            "comment": "Star formation is cool",
            "ddec": 0,
            "dra": 0,
            "epoch": 2020.9232414928438,
            "equinox": 1999.9999085590325,
            "frame": "icrs",
            "mag": {
                "K": 6.7,
                "V": 4.3
            },
            "name": "M42",
            "objecttype": "science",
            "obstime": null,
            "rotmode": "PA",
            "wrap": "shortest",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        }
    ],
    "InstrumentConfigs": [
        {
            "name": "medium BH3 4800 A",
            "arclamp": null,
            "bluecwave": 4800,
            "bluefilter": "KBlue",
            "bluefocus": null,
            "bluegrating": "BH3",
            "bluenandsmask": false,
            "bluepwave": 4500,
            "calmirror": "Sky",
            "calobj": "Dark",
            "detconfig": [
                "KCWIblue 1800s x1",
                "KCWIred 926s x2"
            ],
            "domeflatlamp": null,
            "instrument": "KCWIblue",
            "polarizer": "Sky",
            "redcwave": 6563,
            "redfilter": "KRed",
            "redfocus": null,
            "redgrating": "RH3",
            "rednandsmask": false,
            "redpwave": 6263,
            "slicer": "medium",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "NIRES Instrument Config",
            "detconfig": [
                "NIRES Spec 300s (MCDS32, 1 coadds) x1",
                "NIRES SCAM 10s (CDS, 1 coadds) x6"
            ],
            "instrument": "NIRES",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "arclamp": null,
            "bluecwave": 4800,
            "bluefilter": "KBlue",
            "bluefocus": null,
            "bluegrating": "BH3",
            "bluenandsmask": false,
            "bluepwave": 4500,
            "calmirror": "Sky",
            "calobj": "Dark",
            "domeflatlamp": null,
            "instrument": "KCWI",
            "name": "medium BH3 4800 A",
            "polarizer": "Sky",
            "redcwave": 6563,
            "redfilter": "KRed",
            "redfocus": null,
            "redgrating": "RH3",
            "rednandsmask": false,
            "redpwave": 6263,
            "slicer": "medium",
            "obsid": 9999,
            "semid": "2020B_K999"
        }
    ],
    "DetectorConfigs": [
        {
            "name": "KCWIblue 1800s x1",
            "ampmode": 9,
            "binning": "2x2",
            "dark": false,
            "exptime": 1800,
            "instrument": "KCWIblue",
            "nexp": 1,
            "readoutmode": 0,
            "window": null,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "KCWIred 900s x2",
            "ampmode": 9,
            "binning": "2x2",
            "dark": false,
            "exptime": 900,
            "instrument": "KCWIred",
            "nexp": 2,
            "readoutmode": 0,
            "window": null,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "NIRES SCAM 10s (CDS, 1 coadds) x6",
            "coadds": 1,
            "exptime": 10,
            "instrument": "NIRES SCAM",
            "nexp": 6,
            "readoutmode": "CDS",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "NIRES Spec 300s (MCDS32, 1 coadds) x1",
            "coadds": 1,
            "exptime": 300,
            "instrument": "NIRES Spec",
            "nexp": 1,
            "readoutmode": "MCDS32",
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        }
    ],
    "OffsetPatterns": [
        {},
        {
            "name": "mypattern x1",
            "offsets": [
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 60.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": false,
                    "posname": "sky",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                }
            ],
            "repeat": 1,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "StarSkyStar (60 30) x3",
            "offsets": [
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 60.0,
                    "dy": 30.0,
                    "frame": "SkyFrame",
                    "guide": false,
                    "posname": "sky",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                }
            ],
            "repeat": 3,
            "instr": "KCWI",
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "StarSkyStar (60 30) x3",
            "offsets": [
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 60.0,
                    "dy": 30.0,
                    "frame": "SkyFrame",
                    "guide": false,
                    "posname": "sky",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                }
            ],
            "repeat": 3,
            "obsid": 9999,
            "semid": "2020B_K999"
        },
        {
            "name": "StarSkyStar (60 30) x3",
            "offsets": [
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 60.0,
                    "dy": 30.0,
                    "frame": "SkyFrame",
                    "guide": false,
                    "posname": "sky",
                    "relative": false
                },
                {
                    "dr": 0.0,
                    "dx": 0.0,
                    "dy": 0.0,
                    "frame": "SkyFrame",
                    "guide": true,
                    "posname": "star",
                    "relative": false
                }
            ],
            "repeat": 3,
            "obsid": 9999,
            "semid": "2020B_K999"
        }
    ],
    "Observations": [] }
]
